### ISSUE TITLE
请问添加账号的时候如何区分教师还是学生？

### ISSUE THREAD

**Issue by xingruyubb** [laozhoubuluo/HomeworkManager#2]
请问添加账号的时候如何区分教师还是学生？

**Comment by xingruyubb** [comment]
一直在寻找作业管理系统，终于找到这个比较好的，十分感谢，希望功能能够越来越完善

**Comment by laozhoubuluo** [comment]
这套系统的设计是只有教师有账号，学生没有账号。
学生在上传作业时自行设置学号，姓名，修改或删除密码，只要符合后台设置的学号正则（可选）即可上传成功。
学生对作业的修改均基于他自行设置的修改或删除密码进行。

**Comment by xingruyubb** [comment]
感谢，昨晚我试了一下，确实如此。还有一个问题，有没有这样一个功能，统计某一次作业未交作业的名单

**Comment by laozhoubuluo** [comment]
> 感谢，昨晚我试了一下，确实如此。还有一个问题，有没有这样一个功能，统计某一次作业未交作业的名单

这个需求在这个大框架下确实比较难做，因为数据库里是没有学生名单的，要统计未交作业名单就需要有学生名单，这两者是存在冲突的。
不过系统会把学号从小到大排列，如果学号是连续的可以很容易查到谁交了或者谁没交。

**Comment by xingruyubb** [comment]
哦，明白，非常感谢

**Comment by xingruyubb** [comment]
请问报这个错误是什么原因？
作业上传讯息栏
目录建立失败，请检查目录权限是否可供写入 Err-3	
用Appserv+win7

**Comment by laozhoubuluo** [comment]
> 请问报这个错误是什么原因？
> 作业上传讯息栏
> 目录建立失败，请检查目录权限是否可供写入 Err-3
> 用Appserv+win7

这套程序只在Linux上测试过，没测Windows。
您检查一下init.php里面的路径配置吧，有可能是路径的问题。

**Comment by laozhoubuluo** [comment]
> 请问报这个错误是什么原因？
> 作业上传讯息栏
> 目录建立失败，请检查目录权限是否可供写入 Err-3
> 用Appserv+win7

另外明确一下，这个系统Windows用不了有些功能，比如作业打包是调用zip命令的，Windows里面没有。
