### ISSUE TITLE
无法创建后台用户

### ISSUE THREAD

**Issue by tomriddle1234** [laozhoubuluo/HomeworkManager#4]
默认的后台用户default@note.tc.edu.tw
在创建另一个后台用户时，无论填什么永远都是用户已存在。
用默认后台用户也无法添加任何作业。提示伺服器异常。

PHP 7.1 7.3都试过

**Comment by laozhoubuluo** [comment]
可能我们这边环境比较老，PHP 7.0.33测试正常。
您可以用这个环境测试一下先，我回头准备个高版本环境测试一下。

**Comment by laozhoubuluo** [comment]
您好，经核实由于数据库约束不规范，导致在高版本MySQL下无法创建用户或作业，另外manage.php上的一个小失误导致没有显示出正确的错误原因。
上述Bug已在 https://github.com/laozhoubuluo/HomeworkManager/commit/4ec68854f863cdfae6b9d6864ed248f5c9333480 版本上修复，感谢您的回报！
