### ISSUE TITLE
数据库导入出现错误，不知是何原因？

### ISSUE THREAD

**Issue by xingruyubb** [laozhoubuluo/HomeworkManager#5]
错误
静态分析：

分析时发现3个错误。

A comma or a closing bracket was expected. (near "(" at position 1172)
Unexpected beginning of statement. (near "hID" at position 1173)
Unrecognized statement type. (near "ENGINE" at position 1181)
SQL 查询：

CREATE TABLE IF NOT EXISTS hwList ( hID int(11) NOT NULL auto_increment, hwTitle varchar(100) collate utf8mb4_unicode_ci NOT NULL, hwO varchar(20) collate utf8mb4_unicode_ci NOT NULL, email varchar(60) collate utf8mb4_unicode_ci NOT NULL, classID varchar(50) collate utf8mb4_unicode_ci NOT NULL, remark varchar(1000) collate utf8mb4_unicode_ci NOT NULL, passwd varchar(20) collate utf8mb4_unicode_ci NOT NULL, fromDT datetime NOT NULL, dueDT datetime NOT NULL, display tinyint(4) NOT NULL default '1', closed tinyint(4) NOT NULL default '0', upPasswd tinyint(4) NOT NULL default '0', rank smallint(6) NOT NULL default '20', clicked int(11) NOT NULL DEFAULT 0, uploadCnt mediumint(9) NOT NULL default '0', passedCnt mediumint(9) NOT NULL default '0', lastModDT timestamp NULL default NULL, uDT timestamp NOT NULL default '0000-00-00 00:00:00' on update CURRENT_TIMESTAMP, cDT datetime NOT NULL, cidRegex varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, FileNameFormat varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL, FolderNameFormat varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL PRIMARY KEY (hID) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1

MySQL 返回： 文档

#1067 - Invalid default value for 'FolderNameFormat'

**Comment by laozhoubuluo** [comment]
抱歉，建表语句少了个逗号，请您按 https://github.com/laozhoubuluo/HomeworkManager/commit/c4e743835d9c6ef171ed7963339da59fc739d907 修改SQL文件即可。
