### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by xingruyubb** [laozhoubuluo/HomeworkManager#7]
您好，我想请教一下，为什么只要点下载就会出现如下错误
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in C:\AppServ\www\includes\homework.class.php:201 Stack trace: #0 C:\AppServ\www\homework.php(36): Homework_class->SendFile2Browser(7) #1 {main} thrown in C:\AppServ\www\includes\homework.class.php on line 201

**Comment by laozhoubuluo** [comment]
本程序需要安装并开启 fileinfo 扩展，否则会报错。

**Comment by xingruyubb** [comment]
感谢
